### ISSUE TITLE
New Relic returns 500 error on continuous deployment release

### ISSUE THREAD

**Issue by reallyandrew** [shmulikah/VSTSExtensions#1]
The extension works great if the release deployment is triggered by a real user, but we get it reporting 'The remote server returned an error: (500) Internal Server Error.'  when the release runs on a continuous deployment release under a VSTS service account.

I thought it might be the name of the service account as it is [project]\Project Collection Service Accounts - though this works fine when calling the API directly.

**Comment by shmulikah** [comment]
Thanks for the feedback, I'll check it out and release a fix for it soon, stay tuned

**Comment by shmulikah** [comment]
terribly sorry for the super delayed response .
there is a 31 chars limitation on New Relic side.
